aliases:
  - &docker
      # specify the version you desire here
      - image: circleci/node:8.12.0
  # Circle related commands
  - &restore-cache
    keys:
      - commently-{{ checksum "yarn.lock" }}
  - &save-cache
    key: commently-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules
  # Yarn commands
  - &yarn
    name: Install Dependencies
    command: yarn install --frozen-lockfile --non-interactive --cache-folder=~/.cache/yarn
  - &lint
    name: Lint
    command: yarn lint
  - &test
    name: Test
    command: yarn test
  - &build
    name: Build
    command: yarn build

version: 2
jobs:
  build:
    docker: *docker
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - run: *build

  test:
    docker: *docker
    steps:  
      - checkout
      # Download and cache dependencies
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - run: *test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build